rack time string app
IFilonov/Rack pull request #1
Opened 2019-02-16 20:14 UTC by IFilonov

2019-02-16 23:38 UTC, psylone requested changes

2019-02-16 23:38 UTC, psylone commented on app.rb
> +  def year
Класс который должен отвечать за форматирование времени относится к бизнес логике. Он ничего не знает о том кто и где будет его использовать. Иными словами, rack приложение и класс форматирования времени - это две отдельные сущности. Разнеси их пожалуйста.

2019-02-19 05:21 UTC, BubuntuClu commented on time_format.rb
> +  'year'    => 'year',
есть же специальные обозначение для отдельных частей даты: `%Y` `%m` `%d` `%H` `%M` `%S`
можно их использовать

2019-02-19 05:21 UTC, BubuntuClu commented on time_format.rb
> +      times[-1] = "0" + times[-1] if times[-1].size == 1
тогда не надо будет это делать. собираешь строку из `%Y` `%m` `%d` `%H` `%M` `%S` и потом` Time.now.strftime`

2019-02-19 09:30 UTC, psylone approved these changes

2019-02-19 09:30 UTC, psylone commented on app.rb
> +        bad_formats << format unless TimeFormat::AVAILABLE_FORMATS.include?(format)
Факт того что мы используем константу из `TimeFormat` намекает на то что проверку форматов стоит сделать в классе `TimeFormat`. То есть мы передаём этому классу параметры и класс предоставляет API который позволяет понять есть ли параметры формата, верные ли они, а также получить отформатированное время в качестве результата.

2019-02-21 17:18 UTC, merged